#!/usr/bin/env python3
# Copyright 2026 Christopher Wright
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Derive this device's flash image + symbol table from the uEmu corpus ELF.

The firmware is NOT redistributed by this package (see PROVENANCE.md). Point this
at your local copy of `uEmu.uTasker_MODBUS.out` from
https://github.com/MCUSec/uEmu-real_world_firmware and it writes, into configs/:

  uTaskerMODBUS.bin    the ELF's PT_LOAD segments flattened and zero-padded from
                       0x08000000 so the whole 256 KB flash bank maps as one
                       region (the ELF itself starts at 0x0800c080 -- there is a
                       ~48 KB bootloader region below it that is not in the ELF)
  utasker_addrs.yaml   addr -> name symbol table for intercept resolution
                       (Thumb LSB cleared; FUNC symbols win ties)
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys

EXPECTED_ELF_SHA256 = \
    "1c42831f637ee4749ea8256c39d828f0ee0ac4294c187b914ba1f9b65217055e"
FLASH_BASE = 0x08000000


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("elf", help="path to uEmu.uTasker_MODBUS.out")
    ap.add_argument("--outdir", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src", "rehostry_utasker_modbus", "configs"))
    a = ap.parse_args()

    try:
        from elftools.elf.elffile import ELFFile
    except ImportError:
        print("needs pyelftools:  pip install pyelftools", file=sys.stderr)
        return 1

    raw = open(a.elf, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_ELF_SHA256:
        print(f"warning: ELF sha256 {digest}\n"
              f"         expected {EXPECTED_ELF_SHA256}\n"
              f"         (a different corpus revision may shift addresses)",
              file=sys.stderr)

    elf = ELFFile(open(a.elf, "rb"))
    segs = [(s["p_vaddr"], s.data()) for s in elf.iter_segments()
            if s["p_type"] == "PT_LOAD"]
    hi = max(v + len(d) for v, d in segs)
    img = bytearray(b"\xff" * (hi - FLASH_BASE))
    for v, d in segs:
        img[v - FLASH_BASE:v - FLASH_BASE + len(d)] = d
    binpath = os.path.join(a.outdir, "uTaskerMODBUS.bin")
    open(binpath, "wb").write(img)
    print(f"wrote {binpath}  ({len(img)} bytes, "
          f"sha256 {hashlib.sha256(img).hexdigest()[:16]}...)")

    # symbols: prefer FUNC, then OBJECT; de-prioritise section/mapping symbols
    cands: dict = {}
    for sec in elf.iter_sections():
        if sec.name != ".symtab":
            continue
        for s in sec.iter_symbols():
            v, n, t = s["st_value"], s.name, s["st_info"]["type"]
            if not v or not n or not n.replace("_", "").replace(".", "").isalnum():
                continue
            rank = {"STT_FUNC": 0, "STT_OBJECT": 1}.get(t, 2)
            if n.startswith(".") or n.startswith("$"):
                rank += 5
            cands.setdefault(v & ~1, []).append((rank, n))
    syms = {a_: sorted(v)[0][1] for a_, v in cands.items()}
    ypath = os.path.join(a.outdir, "utasker_addrs.yaml")
    with open(ypath, "w") as fh:
        fh.write("# Generated by tools/extract_firmware.py -- do not edit.\n")
        fh.write("# Symbol table for the uTasker MODBUS-slave firmware (addr <- name).\n")
        fh.write("symbols:\n")
        for v, n in sorted(syms.items()):
            fh.write(f"  {v}: {n}\n")
    print(f"wrote {ypath}  ({len(syms)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
